# Generated by Django 4.2.1 on 2023-06-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_remove_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='created_at',
        ),
    ]
