# Generated by Django 4.2.1 on 2023-06-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_rename_date_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
